name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-app ./.devcontainer

    - name: Install dependencies
      run: npm install

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 2
        done

    - name: Run DB migrations (if any)
      run: |
        npm run migrate  # Adjust this to your migration script if needed

    # - name: Run tests
    #   env:
    #     DATABASE_URL: postgres://postgres:hello1234@localhost:5432/postgres
    #   run: npm test

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build